### ISSUE TITLE
Error on L2C data georeferencing

### ISSUE THREAD

**Issue by safalabolo** [ranghetti/prismaread#7]
Dear Dr. Luigi Ranghetti,

I am attaching the files received after converting using pr_convert.
This is geo-referenced using L2C data which has missing data in it after using this package. 
Could you please check for it?

Thank you.

![image](https://user-images.githubusercontent.com/12288665/134798719-01b3fbea-d1da-49e0-9c6c-6701aac16924.png)

**Comment by safalabolo** [comment]
Below is the link for the download of the processed PRISMA acquisition. Yours sincerely
http://prisma.asi.it/Products/er2kbfsozrg0ognxdl042crndej1uu/PRS_L2C_STD_20210909095202_20210909095206_0001.zip

**Comment by ranghetti** [comment]
Dear Riyaaz,
sorry not to have answered you in #6 but, as you would have seen in the "important note" appeared when you opened this new issue: «The development of this package is frozen, and the current package maintainer cannot provide assistance to users.»

I could try to forward this question to a collegue in next days, but I need a reproducible example. You should provide not only the input and output images, but also the exact code you used.

**Comment by safalabolo** [comment]
Dear Dr. Ranghetti,
thanks for your quick reply!

Below you will find the version of R used (OS Windows 10), the version of R studio and the code used.

The input and output has already been provided.

Thanks in advance for the support.
Yours sincerely.
safalabolo

R version 3.6.3 (2020-02-29) -- "Holding the Windsock"
Copyright (C) 2020 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64 (64-bit)

RStudio Version 1.4.1717


install.packages("remotes")
remotes::install_github("lbusett/prismaread", ref = "v1.0.0",force = TRUE)
library(prismaread)

l2d_he5_path<-'C:/Users/L2B/PRS_L2B_STD_20190603095942_20190603095947_0001.he5'
l2d_out_dir<-'C:/Users//L2B/out'

pr_convert(
  in_file = l2d_he5_path,
  out_folder = l2d_out_dir,
  out_format = "GTiff",
  VNIR = TRUE,
  SWIR = TRUE,
  LATLON = TRUE,
  ANGLES = TRUE
)

**Comment by ranghetti** [comment]
Dear @safalabolo,
I am sorry for the late reply.
I finally had the possibility to deepen this behaviour: I suspect the problem to be related to the argument `fill_gaps`, whose default value is FALSE. can you check it the error will get solved setting `fill_gaps = TRUE` in `pr_convert()`? Otherwise (or in case this would not solve), can you load your image "PRS_L2B_STD_20190603095942_20190603095947_0001.he5" using a WeTransfer, so that I can reproduce your case?

**Comment by ranghetti** [comment]
Dear Eli,
sorry for late reply. You can find a possible solution of your problem in the comment above.
As in that case, can you check in that way or provide me a preproducible example (code + input data loaded using a WeTransfer)?

**Comment by ranghetti** [comment]
I was finally able to reproduce the issue on a different L2B image:
```r
pr_convert(
  in_file = l2d_he5_path,
  out_folder = l2d_out_dir,
  out_format = "GTiff",
  VNIR = TRUE,
  SWIR = TRUE,
  LATLON = TRUE,
  ANGLES = TRUE
)
```
![image](https://user-images.githubusercontent.com/6874239/151588041-8956eae4-b406-497f-ac85-8d1a86efea23.png)

```r
pr_convert(
  in_file = l2d_he5_path,
  out_folder = l2d_out_dir,
  out_format = "GTiff",
  fill_gaps = TRUE,
  VNIR = TRUE,
  SWIR = TRUE,
  LATLON = TRUE,
  ANGLES = TRUE
)
```
![image](https://user-images.githubusercontent.com/6874239/151588060-2763cbf6-b78d-4778-8e9b-3cb08a6111c2.png)

The use of `fill_gaps = TRUE` will solve the issue.

**Comment by safalabolo** [comment]
Dear, Thank You very much for this!
